# 13장 연습문제 풀이 -임해찬

In [1]:
# ■ 다음은 교육부에서 제공한 전국 고등학교의 학년별 학급수와 학생수 정보(2019년 기준)를
# 저장한 파일이다. 다음 물음에 답하시오.(1~4번 문제)

In [1]:
# 1. high_school_2019.csv 파일을 읽어들여 2차원 리스트에 저장한 다음 출력하는 프로그램을
#    작성하시오.
import csv

f = open('high_school_2019.csv', 'r', encoding='utf-8')
lines = csv.reader(f)

header = next(lines)
print(header)

list_data = []
for line in lines :
    list_data.append(line[:])

list_data
f.close()

['지역', ' 학교명', ' 1학년 학급수', ' 1학년 학생수', ' 2학년 학급수', ' 2학년 학생수', ' 3학년 학급수', ' 3학년 학생수']


In [14]:
# 2. 1번에서 저장된 2차원 리스트 데이터 중에서 숫자 데이터에 해당되는 6개의 열
#    (1학년 학급수, 1학년 학생수, 2학년 학생수, 3학년 학급수, 3학년 학생수) 데이터를
#    ndarray에 저장하는 프로그램을 작성하시오.
import csv
import numpy as np

f = open('high_school_2019.csv', 'r', encoding='utf-8')
lines = csv.reader(f)

header = next(lines)

list_data = []
for line in lines :
    list_data.append(line[:])

length = len(list_data)
print('-' * 72)
print('1학년 학급수 1학년 학생수 2학년 학급수 2학년 학생수 3학년 학급수 3학년 학생수')
print('-' * 72)
data = np.zeros((length, 6), dtype='int32')

for i in range(length) :
    for j in range(6) :
        data[i][j] = list_data[i][j+2]
        
print(data)

f.close()

------------------------------------------------------------------------
1학년 학급수 1학년 학생수 2학년 학급수 2학년 학생수 3학년 학급수 3학년 학생수
------------------------------------------------------------------------
[[  5 150   5 149   5 143]
 [  8 239   8 228   8 270]
 [  6 182   6 174   6 169]
 ...
 [  4  76   5  91   5 103]
 [  4  99   4  95   4  92]
 [  5 116   5  98   5 126]]


In [15]:
# 3. 전국의 고등학교에 대해 각 학교의 총 학생수(1,2,3학년 학생수의 합)를 구해 마지막에 열에
#    삽입하는 프로그램을 작성하시오.
import csv
import numpy as np

f = open('high_school_2019.csv', 'r', encoding='utf-8')
lines = csv.reader(f)

header = next(lines)

list_data = []
for line in lines :
    list_data.append(line[:])

length = len(list_data)

print('-' * 72)
print('1학년 학급수 1학년 학생수 2학년 학급수 2학년 학생수 3학년 학급수 3학년 학생수')
print('-' * 72)
data = np.zeros((length, 6), dtype='int32')

for i in range(length) :
    for j in range(6) :
        data[i][j] = list_data[i][j+2]
        
print(data)

f.close()

2398
------------------------------------------------------------------------
1학년 학급수 1학년 학생수 2학년 학급수 2학년 학생수 3학년 학급수 3학년 학생수
------------------------------------------------------------------------
[[  5 150   5 149   5 143]
 [  8 239   8 228   8 270]
 [  6 182   6 174   6 169]
 ...
 [  4  76   5  91   5 103]
 [  4  99   4  95   4  92]
 [  5 116   5  98   5 126]]
